networks:
  a2a-internal:
    driver: bridge

services:
  a2a-app:
    build:
      args:
        user: lps
        uid: 1000
      context: ./
      dockerfile: ./.docker/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - a2a-internal
  a2a-db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: a2a_theaters
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - a2a-internal
  a2a-nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - a2a-internal